# Generated by Django 4.2.27 on 2025-12-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='premium_content',
            field=models.TextField(blank=True),
        ),
    ]
