# Generated by Django 4.2.27 on 2025-12-09 13:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-updated'], 'verbose_name_plural': 'Portfolio'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_caption',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
